name=input("Введите имя")
ago=input("Введите возраст")
hobbi=input("Введите своё хобби")
city=input("Вашь город")
nomer=input("Введите свой номер телефона")
print(f"Это {name}, ему {ago},живет он в городе {city}, у него хобби {hobbi} и у него такой номер телефона {nomer}")